/**
 * Pi Generator Orchestrator
 *
 * Discovers Ensemble YAML sources across packages/*, validates structural
 * requirements, calls transformers, and writes Pi-compatible artifacts to
 * packages/pi/prompts/, agents/, skills/, and AGENTS.md.
 *
 * Supports --dry-run (collect without writing), --verbose (log paths),
 * and --validate (parse output .md files after generation).
 *
 * @module ensemble-pi/generator
 */

import { GeneratorOptions, TransformResult, CommandYaml, AgentYaml } from './types';
import * as path from 'path';
import * as fs from 'fs';
import * as yaml from 'js-yaml';
import { glob } from 'glob';

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Recursively collect files matching an extension under a directory.
 * Used as a fallback if glob is unavailable, but glob is preferred.
 */
function findFilesRecursive(dir: string, ext: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findFilesRecursive(full, ext));
    } else if (entry.isFile() && entry.name.endsWith(ext)) {
      results.push(full);
    }
  }
  return results;
}

/**
 * Discover YAML files matching a glob pattern.
 * Returns absolute paths sorted lexicographically for deterministic output.
 */
async function discoverYamlFiles(pattern: string): Promise<string[]> {
  const files = await glob(pattern, { absolute: true });
  return files.sort();
}

// ---------------------------------------------------------------------------
// Structural validation
// ---------------------------------------------------------------------------

/**
 * Validate required fields in a parsed command YAML.
 * Throws with a specific message if any required field is absent.
 */
function validateCommandYaml(data: unknown, filePath: string): CommandYaml {
  const d = data as Record<string, unknown>;

  const requiredFields: Array<{ fieldName: string; present: boolean }> = [
    {
      fieldName: 'metadata.name',
      present:
        typeof d?.metadata === 'object' &&
        d.metadata !== null &&
        typeof (d.metadata as Record<string, unknown>).name === 'string' &&
        (d.metadata as Record<string, unknown>).name !== '',
    },
    {
      fieldName: 'metadata.version',
      present:
        typeof d?.metadata === 'object' &&
        d.metadata !== null &&
        typeof (d.metadata as Record<string, unknown>).version === 'string' &&
        (d.metadata as Record<string, unknown>).version !== '',
    },
    {
      fieldName: 'workflow.phases',
      present:
        typeof d?.workflow === 'object' &&
        d.workflow !== null &&
        Array.isArray((d.workflow as Record<string, unknown>).phases),
    },
  ];

  for (const { fieldName, present } of requiredFields) {
    if (!present) {
      throw new Error(`Missing required field: ${fieldName} in ${filePath}`);
    }
  }

  return d as unknown as CommandYaml;
}

// ---------------------------------------------------------------------------
// Placeholder transformers (stubs — expanded in TRD-006a, TRD-007, TRD-008)
// ---------------------------------------------------------------------------

/**
 * Transform a command YAML into a Pi prompt markdown string.
 * This stub is intentionally minimal; TRD-006a implements the full transform.
 */
function transformCommand(
  commandYaml: CommandYaml,
  sourcePath: string,
  outputRoot: string
): TransformResult {
  const name = commandYaml.metadata.name;
  // Normalise "ensemble:command-name" → "ensemble-command-name" for filesystem safety
  const safeName = name.replace(/:/g, '-');
  const outputPath = path.join(outputRoot, 'prompts', `${safeName}.md`);

  // Minimal stub content — TRD-006a will replace this with full rendering
  const content = [
    `# ${name}`,
    '',
    `> v${commandYaml.metadata.version}`,
    '',
    commandYaml.metadata.description ?? '',
    '',
    '<!-- Generated by ensemble-pi — full rendering implemented in TRD-006a -->',
  ].join('\n');

  return { sourcePath, outputPath, content, type: 'command' };
}

/**
 * Transform an agent YAML into a Pi agent markdown string.
 * This stub is intentionally minimal; TRD-007 implements the full transform.
 */
function transformAgent(
  agentYaml: AgentYaml,
  sourcePath: string,
  outputRoot: string
): TransformResult {
  const safeName = agentYaml.name.replace(/\s+/g, '-').toLowerCase();
  const outputPath = path.join(outputRoot, 'agents', `${safeName}.md`);

  const content = [
    `# ${agentYaml.name}`,
    '',
    agentYaml.description ?? '',
    '',
    '<!-- Generated by ensemble-pi — full rendering implemented in TRD-007 -->',
  ].join('\n');

  return { sourcePath, outputPath, content, type: 'agent' };
}

// ---------------------------------------------------------------------------
// File I/O
// ---------------------------------------------------------------------------

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function writeResult(result: TransformResult): void {
  ensureDir(path.dirname(result.outputPath));
  fs.writeFileSync(result.outputPath, result.content, 'utf-8');
}

// ---------------------------------------------------------------------------
// --validate pass: parse output .md files for structural issues
// ---------------------------------------------------------------------------

function validateOutputFiles(outputRoot: string): void {
  const mdFiles = findFilesRecursive(outputRoot, '.md');
  const errors: string[] = [];

  for (const mdFile of mdFiles) {
    try {
      const content = fs.readFileSync(mdFile, 'utf-8');
      // Basic validation: file must be non-empty and start with a heading
      if (!content.trim()) {
        errors.push(`${mdFile}: file is empty`);
      } else if (!content.trimStart().startsWith('#')) {
        errors.push(`${mdFile}: does not start with a markdown heading`);
      }
    } catch (err) {
      errors.push(`${mdFile}: read error — ${(err as Error).message}`);
    }
  }

  if (errors.length > 0) {
    process.stderr.write(`Validation found ${errors.length} issue(s):\n`);
    for (const e of errors) {
      process.stderr.write(`  - ${e}\n`);
    }
  } else {
    process.stdout.write(`Validation passed: ${mdFiles.length} output file(s) OK.\n`);
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function generate(options: GeneratorOptions): Promise<void> {
  const { dryRun, verbose, validate, sourceRoot, outputRoot } = options;

  if (verbose) {
    process.stdout.write('Pi generator starting...\n');
    process.stdout.write(`Source root: ${sourceRoot}\n`);
    process.stdout.write(`Output root: ${outputRoot}\n`);
    process.stdout.write(
      `Flags: dry-run=${dryRun}, verbose=${verbose}, validate=${validate}\n`
    );
  }

  const results: TransformResult[] = [];

  // ------------------------------------------------------------------
  // 1. Discover and process command YAML files
  // ------------------------------------------------------------------
  const commandPattern = path.join(sourceRoot, 'packages/*/commands/*.yaml');
  const commandFiles = await discoverYamlFiles(commandPattern);

  if (verbose) {
    process.stdout.write(`Discovered ${commandFiles.length} command YAML file(s).\n`);
  }

  for (const filePath of commandFiles) {
    let raw: unknown;
    try {
      raw = yaml.load(fs.readFileSync(filePath, 'utf-8'));
    } catch (err) {
      throw new Error(`YAML parse error in ${filePath}: ${(err as Error).message}`);
    }

    // Structural validation runs BEFORE any transformation (TRD-005 requirement)
    const commandYaml = validateCommandYaml(raw, filePath);
    const result = transformCommand(commandYaml, filePath, outputRoot);

    if (verbose) {
      process.stdout.write(`  command: ${filePath} → ${result.outputPath}\n`);
    }

    results.push(result);
  }

  // ------------------------------------------------------------------
  // 2. Discover and process agent YAML files
  // ------------------------------------------------------------------
  const agentPattern = path.join(sourceRoot, 'packages/*/agents/*.yaml');
  const agentFiles = await discoverYamlFiles(agentPattern);

  if (verbose) {
    process.stdout.write(`Discovered ${agentFiles.length} agent YAML file(s).\n`);
  }

  for (const filePath of agentFiles) {
    let raw: unknown;
    try {
      raw = yaml.load(fs.readFileSync(filePath, 'utf-8'));
    } catch (err) {
      throw new Error(`YAML parse error in ${filePath}: ${(err as Error).message}`);
    }

    if (!raw || typeof raw !== 'object') {
      // Skip malformed agent files rather than aborting the entire run
      if (verbose) {
        process.stderr.write(`  agent: skipping ${filePath} (empty or non-object YAML)\n`);
      }
      continue;
    }

    // Agent YAML files may use either top-level `name` or the nested
    // `metadata.name` + `metadata.description` layout used across the monorepo.
    const rawObj = raw as Record<string, unknown>;
    let agentYaml: AgentYaml;

    if (rawObj.metadata && typeof rawObj.metadata === 'object') {
      const meta = rawObj.metadata as Record<string, unknown>;
      agentYaml = {
        name: (meta.name as string) ?? '',
        description: (meta.description as string) ?? '',
        tools: (rawObj.tools as string[]) ?? (meta.tools as string[]) ?? [],
        model: (meta.model as string) ?? undefined,
      };
    } else {
      agentYaml = raw as AgentYaml;
    }

    if (!agentYaml.name) {
      if (verbose) {
        process.stderr.write(`  agent: skipping ${filePath} (missing name field)\n`);
      }
      continue;
    }

    const result = transformAgent(agentYaml, filePath, outputRoot);

    if (verbose) {
      process.stdout.write(`  agent: ${filePath} → ${result.outputPath}\n`);
    }

    results.push(result);
  }

  // ------------------------------------------------------------------
  // 3. Skill files — TRD-008 will implement the full copier
  // ------------------------------------------------------------------
  if (verbose) {
    process.stdout.write('Skill copy: deferred to TRD-008.\n');
  }

  // ------------------------------------------------------------------
  // 4. AGENTS.md generation — TRD-009 will implement this
  // ------------------------------------------------------------------
  if (verbose) {
    process.stdout.write('AGENTS.md generation: deferred to TRD-009.\n');
  }

  // ------------------------------------------------------------------
  // 5. Write results (unless --dry-run)
  // ------------------------------------------------------------------
  if (!dryRun) {
    for (const result of results) {
      writeResult(result);
    }
  } else if (verbose) {
    process.stdout.write(
      `Dry-run mode: ${results.length} artifact(s) collected but not written.\n`
    );
  }

  // ------------------------------------------------------------------
  // 6. --validate: parse all output .md files and report errors
  // ------------------------------------------------------------------
  if (validate && !dryRun) {
    validateOutputFiles(outputRoot);
  }

  if (verbose) {
    process.stdout.write(
      `Generator complete. ${results.length} artifact(s) processed.\n`
    );
  }
}
